apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"backend-app-reader"},"rules":[{"apiGroups":[""],"resources":["pods"],"verbs":["get","list"]},{"apiGroups":["apps"],"resources":["deployments"],"verbs":["get","list","create","update","patch","delete"]},{"apiGroups":[""],"resources":["services"],"verbs":["get","list","create","update","delete"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["get","list","create","update","delete"]},{"apiGroups":[""],"resources":["persistentvolumeclaims"],"verbs":["get","list","create","delete"]},{"apiGroups":["batch"],"resources":["jobs"],"verbs":["get","list","create","delete"]}]}
  creationTimestamp: "2026-08-17T15:44:24Z"
  name: backend-app-reader
  resourceVersion: "12226088"
  uid: 557f0946-83fb-4cb7-85ed-bc34da959bf2
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - configmaps
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
