apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.af-casablanca-1.aaaaaaaa65dwcrjjkmomz5g5vxones4k3bdskwdfpe2jf7mnvgabxedk6bfq"
spec:
  type: LoadBalancer
  selector:
    app: model-service
  ports:
    - name: http
      port: 80
      targetPort: 8000