apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: model-service
          image: lej.ocir.io/axi6dz7sdr1m/model-service:v1
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.af-casablanca-1.aaaaaaaa65dwcrjjkmomz5g5vxones4k3bdskwdfpe2jf7mnvgabxedk6bfq"
spec:
  type: LoadBalancer
  selector:
    app: model-service
  ports:
    - port: 80
      targetPort: 8000
