apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: model-service
          image: ghcr.io/hassanfasseh/vela/model-service:f78ec937703f79447d627b9a2c630fb8f448b411
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
