"""add username is_admin force_password_change tickets

Revision ID: 6ea9c0e1dc8f
Revises: fd073882ff22
Create Date: 2026-08-23 11:11:58.427756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea9c0e1dc8f'
down_revision: Union[str, Sequence[str], None] = 'fd073882ff22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ticket_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('filed_by', sa.Integer(), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['filed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.add_column('workspace_api_keys', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('workspace_api_keys', sa.Column('deployment_id', sa.Integer(), nullable=True))
    op.add_column('workspace_api_keys', sa.Column('description', sa.String(length=200), nullable=False))
    op.create_foreign_key(None, 'workspace_api_keys', 'deployments', ['deployment_id'], ['id'])
    op.create_foreign_key(None, 'workspace_api_keys', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_api_keys', type_='foreignkey')
    op.drop_constraint(None, 'workspace_api_keys', type_='foreignkey')
    op.drop_column('workspace_api_keys', 'description')
    op.drop_column('workspace_api_keys', 'deployment_id')
    op.drop_column('workspace_api_keys', 'team_id')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'username')
    op.drop_table('tickets')
    # ### end Alembic commands ###
