"""add custom model fields to deployments

Revision ID: d093d7212ede
Revises: 143338acaa37
Create Date: 2026-08-24 01:31:07.029837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd093d7212ede'
down_revision: Union[str, Sequence[str], None] = '143338acaa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('input_type', sa.String(length=20), nullable=False, server_default='text'))
    op.add_column('deployments', sa.Column('model_type', sa.String(length=20), nullable=False, server_default='huggingface'))
    op.add_column('deployments', sa.Column('minio_path', sa.String(length=500), nullable=True))
    op.add_column('deployments', sa.Column('input_schema', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'input_schema')
    op.drop_column('deployments', 'minio_path')
    op.drop_column('deployments', 'model_type')
    op.drop_column('deployments', 'input_type')
    # ### end Alembic commands ###
