apiVersion: v1
kind: Service
metadata:
  name: backend-app
  namespace: {{ include "vela.namespace" . }}
  labels:
    app: backend-app
    {{- include "vela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend-app
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
{{- if .Values.backend.externalService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-external
  namespace: {{ include "vela.namespace" . }}
  labels:
    app: backend-app
    {{- include "vela.labels" . | nindent 4 }}
  {{- with .Values.backend.externalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.externalService.type }}
  selector:
    app: backend-app
  ports:
    - name: http
      port: {{ .Values.backend.externalService.port }}
      targetPort: {{ .Values.backend.externalService.targetPort }}
{{- end }}
