{{- if not .Values.production.externalDatabase.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ include "vela.namespace" . }}
  labels:
    app: postgres
    {{- include "vela.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.database.storageClassName }}
  storageClassName: {{ .Values.database.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}
{{- end }}
